package com.duan.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.duan.wanandroid.bean.MuchBean;
import com.duan.wanandroid.bean.StuentBean;
import com.duan.wanandroid.bean.UserBean;

import com.duan.greenDao.MuchBeanDao;
import com.duan.greenDao.StuentBeanDao;
import com.duan.greenDao.UserBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig muchBeanDaoConfig;
    private final DaoConfig stuentBeanDaoConfig;
    private final DaoConfig userBeanDaoConfig;

    private final MuchBeanDao muchBeanDao;
    private final StuentBeanDao stuentBeanDao;
    private final UserBeanDao userBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        muchBeanDaoConfig = daoConfigMap.get(MuchBeanDao.class).clone();
        muchBeanDaoConfig.initIdentityScope(type);

        stuentBeanDaoConfig = daoConfigMap.get(StuentBeanDao.class).clone();
        stuentBeanDaoConfig.initIdentityScope(type);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        muchBeanDao = new MuchBeanDao(muchBeanDaoConfig, this);
        stuentBeanDao = new StuentBeanDao(stuentBeanDaoConfig, this);
        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);

        registerDao(MuchBean.class, muchBeanDao);
        registerDao(StuentBean.class, stuentBeanDao);
        registerDao(UserBean.class, userBeanDao);
    }
    
    public void clear() {
        muchBeanDaoConfig.clearIdentityScope();
        stuentBeanDaoConfig.clearIdentityScope();
        userBeanDaoConfig.clearIdentityScope();
    }

    public MuchBeanDao getMuchBeanDao() {
        return muchBeanDao;
    }

    public StuentBeanDao getStuentBeanDao() {
        return stuentBeanDao;
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

}
